// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Department struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Teams []*Team `json:"teams"`
}

type NewDepartment struct {
	Name string `json:"name"`
}

type NewService struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	TeamID      string `json:"teamID"`
}

type NewTeam struct {
	Name        string `json:"name"`
	DeparmentID string `json:"deparmentID"`
}

type Service struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Team        *Team  `json:"team"`
}

type Team struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Deparment *Department `json:"deparment"`
	Services  []*Service  `json:"services"`
}
